name: Build docker image and publish on docker hub

on: workflow_dispatch

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # git hub 에 해당 리파지토리에 setting에서 설정할 수 있다. 이거 내 아이디 magicq6265 이다.
          password: ${{ secrets.DOCKERHUB_TOKEN }} # 위와 같이 설정을 해주는데 token은 docker hub에서 받을 수 있다.

      - name: Setting environment variables
        run: |
          chmod +x ./scripts/set-env.sh
          ./scripts/set-env.sh
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          COOKIE_DOMAIN_PROD: ${{secrets.COOKIE_DOMAIN_PROD}}

      - name: Building docker image
        run: make build

      - name: Publishing docker image
        run: make push